[package]
name = "rust_todo_mariadb"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "22.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
